### ISSUE TITLE
WHERE INSTALL??

### ISSUE THREAD

**Issue by cedricalpatch** [mraes/fivem-mapeditor#1]
hello sorry but where I install this ... I have install the resources and all work but not save map!?
For .cs file etc I have put in root of Fivem.

Can you help me?

Thanks

**Comment by mraes** [comment]
https://github.com/mraes/fivem-mapeditor/releases/tag/0.5

**Comment by cedricalpatch** [comment]
ok so this good but the save dont work? I see in map folder and all my server but not .xml file...

**Comment by cedricalpatch** [comment]
I have this error?
https://media.discordapp.net/attachments/343471925731000320/378531642169622528/Capture.PNG?width=745&height=597

**Comment by mraes** [comment]
No idea. I haven't touched this code or FiveM in a while. When I get back to it I'll fix it.
Bear in mind I haven't released this resource exactly for the reason that it isn't finished yet.

**Comment by cedricalpatch** [comment]
ok no problem I wait, thank you...

**Comment by cedricalpatch** [comment]
hello 

you have news?
